user_name: "ssj4justdale"                # Name of the user you are connecting as (messages will be sent via this user)
channel_name: "pTLucy"             # Name of the channel this bot is working on (can be same as the user name, if the streamer wants to post messages as himself)
usage_message: "$(username), usage: !songrequest song-link (Spotify -> Share -> Copy Song Link)"  # Command is called without any arguments
wrong_format_message: "$(username), sorry, but only Spotify Share URLs are supported"             # Command arguments are not recognized as a Spotify share link URL
added_to_queue_message: "\"$(artists) - $(trackName)\" is added to the queue ptlucyANGRYGOOSE"                  # Successfully added the song to the queue
custom_reward_id: "4lvx2374lvx2374lvx237"  # reward ID for the Channel Points redemption. Required to be set if usage_type is channel_points
express_port: 3001
logs: TRUE
usage_type: "command" # can be either "channel_points", "command" or "bits"
command_alias: "!sr" # can be switched to something custom like "!sr" for brevity
use_song_command: FALSE # add !song command that displays currently playing song. FALSE if you don't want it
minimum_requred_bits: 1 # works if usage mode is set to "bits"
spotify_client_id: ""
spotify_client_secret: ""
song_requests_toggle_enable_command: "!srtoggle"
song_requests_skip_current_track_command: "!srskip"
# song_requests_toggle_playback_command: "!srtogglepause"
song_requests_toggle_playback_command: "!kjasdfjkfsdajihsdfayhu734ruifdsa8u943589utrfeij"


# List of ENV variables required at the start:
# SPOTIFY_CLIENT_ID
# SPOTIFY_CLIENT_SECRET
# TWITCH_OAUTH_TOKEN
